routes/web.php
<?php

use App\Http\Controllers\CommentController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontEnd.index');
});

Route::get('/faq', function () {
    return view('frontEnd.faq');
});

Route::get('/blog', function () {
    return view('frontEnd.blog');
});

Route::get('/payment', function () {
    return view('frontEnd.payment');
});

Route::get('/checkout', function () {
    return view('frontEnd.checkout');
});

Route::get('/contact', function () {
    return view('frontEnd.contact');
});

Route::get('/single', function () {
    return view('frontEnd.single');
});

Route::get('/shop', function () {
    return view('frontEnd.shop');
});

Route::get('/product_view', function () {
    return view('frontEnd.product_view');
});

Route::get('/products', function () {
    return view('frontEnd.products');
});

Route::get('/about', function () {
    return view('frontEnd.about');
});





Route::group(['prefix' => 'admin','middleware'=>'auth'], function () {

    Route::get('category/pdf', 'PdfController@category')->name('category.pdf');
    Route::get('category/exel', 'ExelController@category')->name('category.exel');

    Route::get('product/pdf', 'PdfController@category')->name('product.pdf');
    Route::get('product/exel', 'ExelController@category')->name('product.exel');

    Route::put('trashRestore/{id}' , 'softDeleteController@trashRestore')->name('cetagori.trashRestore');

    Route::delete('trashDelete/{id}' , 'softDeleteController@trashDelete')->name('cetagori.trashDelete');



    // Route::put('trashRestore/{id}' , 'softDeleteController@trashRestore')->name('product.trashRestore');

    // Route::delete('trashDelete/{id}' , 'softDeleteController@trashDelete')->name('product.trashDelete');

    Route::get('trashlist' , 'softDeleteController@trashList')->name('product.trashlist');

    Route::get('trashlist' , 'softDeleteController@trashList')->name('categori.trashlist');



    Route::resource('categori', 'CategoriController');
    Route::resource('product', 'ProductController');
    Route::resource('blog', 'BlogController');
    Route::get('color/test', 'ColorController@test');



    Route::get('dashboard', 'HomeController@index')->name('admin/dashboard');

    Route::get('my-profile', 'UserController@myProfile')->name('my_profile');
    Route::put('update-profile', 'UserController@updateProfile')->name('update_profile');

    Route::post('product/{product}/comment', 'CommentController@product')->name('product/comment') ;

});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Categori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Categori extends Model
{

    use SoftDeletes;
    protected $fillable = ['status','title','description'];
    public function products(){
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoriController.php
<?php

namespace App\Http\Controllers;

use App\Categori;
use Illuminate\Http\Request;

class CategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $categoris = Categori::latest()->get();
        return view('backend.admin.categori.index',compact('categoris'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.admin.categori.crieate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Categori::create($request->all());
        return redirect (route('categori.index'))->with('success','insart successful');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $show = Categori::find($id);

        return view('backend.admin.categori.show',compact('show'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Categori::find($id);
        return view('backend.admin.categori.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Categori::find($id);
        $update->update($request->all());
        return redirect (route('categori.index'))->with('success','Updated successful');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Categori::find($id);
        $delete->delete();
        return redirect()->back()->with('danger','Moved To Trash-List');
    }
}

resources/views/backend/admin/categori/crieate.blade.php
@extends('backend/layouts/master')
@section('title','ADD CATEGORI')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="card-body">
                <h4 class="ml-2">ADD NEW CATEGORI</h4>
                <hr>
                <form action="{{route('categori.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group col-4">
                        <label for="active">Active?</label>
                        <select class="form-control" name="status"
                        id="active">
                          <option value="1">Active</option>
                          <option value="0">Not-Active</option>
                        </select>
                      </div>
                    <div class="form-group form-float col-12">
                        <div class="form-line">
                            <label for="name">Title</label>
                            <input type="text" id="name" name="title" class="form-control" required placeholder="Categori Title">
                        </div>
                    </div>
                    <div class="form-group form-float col-12">
                        <div class="form-line">
                            <label for="Description">Description</label>
                            <textarea name="description" id="Description" cols="143"  rows="3">
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group form-float col-12">
                        <div class="form-line">
                            <label for="image">Image</label><br>
                            <input type="file" id="image" name="image" class="form-control" required>
                        </div>
                    </div>
                    <div class="form-group form-float col-12">
                         <a href="{{route('categori.index')}}" class="btn btn-danger m-t-15 waves-effect">
                        <i class="fas fa-backward mr-1"></i>
                            <span>BACK</span>
                        </a>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">
                        <i class="fas fa-plus mr-1"></i>
                        <span>ADD</span>
                    </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
    {{-- <script src="{{asset('ui/backend')}}/libs/footable/footable.all.min.js"></script>

<!-- Init js -->
<script src="{{asset('ui/backend')}}/js/pages/foo-tables.init.js"></script> --}}
@endpush

resources/views/backend/admin/categori/edit.blade.php
@extends('backend/layouts/master')
@section('title','EDIT CATEGORY')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="card-body">
                <h4 class="ml-2">ADD NEW CATEGORY</h4>
                <hr>
                <form action="{{route('categori.update',$category->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group col-4">
                        <label for="active">Active?</label>
                        <select class="form-control" name="status"
                        id="active">
                          <option value="1">Active</option>
                          <option value="0">Not-Active</option>
                        </select>
                      </div>
                    <div class="form-group form-float col-12">

                        <div class="form-line">
                            <label for="name">Title</label>
                        <input type="text" id="name" name="title" class="form-control" required value="{{$category->title}}">
                        </div>
                    </div>
                    <div class="form-group form-float col-12">
                        <div class="form-line">
                            <label for="Description">Description</label>
                            <textarea name="description" id="Description" cols="143"  rows="3">
                                {{$category->description}}
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group form-float col-12">
                         <a href="{{route('categori.index')}}" class="btn btn-danger m-t-15 waves-effect">
                        <i class="fas fa-backward mr-1"></i>
                            <span>BACK</span>
                        </a>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">
                        <i class="fas fa-plus mr-1"></i>
                        <span>UPDATE</span>
                    </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')

@endpush

resources/views/backend/admin/categori/index.blade.php
@extends('backend/layouts/master')
@section('title','categori-list')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card-box">
            <h4 class="header-title">Categori-List</h4>
           <hr>
            <div class="mb-2">
                <div class="row">
                    <div class="col-8 text-sm-center form-inline">
                        <a href="{{route('category.pdf')}}" type="button" class="btn btn-secondary mr-1">
                            <i class="fas fa-download"></i>
                            <span>PDF</span>
                        </a>
                        <a href="{{route('category.exel')}}" type="button" class="btn btn-secondary">
                            <i class="fas fa-download"></i>
                            <span>EXEL</span>
                        </a>
                    </div>
                    <div class=" col-4 ">
                        <a href="{{route('categori.create')}}" type="button" class="btn btn-outline-info">
                            <i class="fas fa-plus"></i>
                            <span>ADD NEW CATEGORI</span>
                        </a>
                        <a href="{{route('categori.trashlist')}}" type="button" class="btn btn-outline-danger">
                            <i class="fas fa-trash"></i>
                            <span>TRASH LIST</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="">
                <table id="demo-foo-filtering" class="table toggle-circle mb-0 table-striped " data-page-size="7">
                    <tr>
                        <th >Id</th>
                        <th>Title</th>
                        <th >Description</th>
                        <th >Status</th>
                        <th >Action</th>
                    </tr>
                        @foreach ($categoris as $key=>$categori)
                    <tr>
                        <td>{{$key+1}}</td>
                        <td>{{$categori->title}}</td>
                        <td>{{ Str::limit($categori->description, 50) }}</td>
                        {{-- {{$categori->description}} --}}
                        <td>
                            @if ($categori->status == 1)
                                {{ "Active" }}
                            @else
                                {{"Not-Active"}}
                            @endif
                        </td>
                        <td class="d-flex">
                            <span>
                            <a href="{{route('categori.show',$categori->id)}}" type="button" class="btn btn-outline-primary mr-1">
                                <i class="fas fa-eye"></i>
                                </a>
                            </span>
                            <span>
                                <a href="{{route('categori.edit',$categori->id)}}" type="button" class="btn btn-outline-success mr-1 ">
                                <i class="fas fa-edit"></i>
                                </a>
                            </span>
                            <span>
                                <form action="{{route('categori.destroy',$categori->id)}}" method="post">
                                    @csrf
                                    @method('Delete')
                                    <button class="btn btn-outline-danger" type="submit" onclick="return confirm('Are you sure you want to delete this item?');">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </span>
                        </td>
                    </tr>
                    @endforeach
                </table>

            </div> <!-- end .table-responsive-->
        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>
@endsection

@push('js')
    <script src="{{asset('ui/backend')}}/libs/footable/footable.all.min.js"></script>

<!-- Init js -->
<script src="{{asset('ui/backend')}}/js/pages/foo-tables.init.js"></script>
@endpush

resources/views/backend/admin/categori/pdfGenaretor.blade.php
<div class="row">
    <div class="col-12">
        <div class="card-box">
            <h4 class="header-title">Categori-List</h4>
           <hr>

            <div class="">
                <table id="demo-foo-filtering" class="table toggle-circle mb-0 table-striped " data-page-size="7">
                    <tr>
                        <th >Id</th>
                        <th>Title</th>
                        <th >Description</th>
                        <th >Status</th>
                    </tr>
                        @foreach ($categoris as $key=>$categori)
                    <tr>
                        <td>{{$key+1}}</td>
                        <td>{{$categori->title}}</td>
                        <td>{{$categori->description}}</td>
                        <td>
                            @if ($categori->status == 1)
                                {{ "Active" }}
                            @else
                                {{"Not-Active"}}
                            @endif
                        </td>
                    </tr>
                    @endforeach

                </table>

            </div> <!-- end .table-responsive-->
        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

resources/views/backend/admin/categori/show.blade.php
@extends('backend/layouts/master')
@section('title','Categori')
@section('content')
<div class="row">
    <div class=" col-12">
         <div class="card">
        <div class="card-body">
            <table id="demo-foo-filtering" class="table toggle-circle mb-0 table-striped " data-page-size="7">
                <tr>
                    <th >Title</th>
                    <td>{{$show->title}}</th>
                </tr>
                <tr>
                    <th >Description</th>
                    <td>{{$show->description}}</th>
                </tr>
                <tr>
                    <th >Products</th>
                    <td>
                        <ul>
                            @foreach ($show->products as $product)
                                <li>{{$product->title}}</li>
                            @endforeach
                        </ul>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    </div>

</div>
@endsection

@push('js')
    {{-- <script src="{{asset('ui/backend')}}/libs/footable/footable.all.min.js"></script>

<!-- Init js -->
<script src="{{asset('ui/backend')}}/js/pages/foo-tables.init.js"></script> --}}
@endpush

resources/views/backend/admin/categori/trashList.blade.php
@extends('backend/layouts/master')
@section('title','categori-Trash')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card-box">
            <h4 class="header-title">Categori-Trash</h4>
           <hr>
            <div class="mb-2">
                <div class="row">
                    <div class="col-9 text-sm-center form-inline">
                        <div class="form-group mr-2">
                            <select id="demo-foo-filter-status" class="custom-select custom-select-sm">
                                <option value="">Show all</option>
                                <option value="active">Active</option>
                                <option value="disabled">Disabled</option>
                                <option value="suspended">Suspended</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input id="demo-foo-search" type="text" placeholder="Search" class="form-control form-control-sm" autocomplete="on">
                        </div>
                    </div>
                    <div class="col-3 float-left">
                        <a href="{{route('categori.index')}}" type="button" class="btn btn-outline-primary">
                            <i class="fas fa-plus"></i>
                            <span>CATEGORY-LIST</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="">
                <table id="demo-foo-filtering" class="table toggle-circle mb-0 table-striped " data-page-size="7">
                    <tr>
                        <th >Id</th>
                        <th>Title</th>
                        <th >Description</th>
                        <th class="d-flex justify-content-center" >Action</th>
                    </tr>
                        @foreach ($trashs as $key=>$trash)
                    <tr>
                        <td>{{$key+1}}</td>
                        <td>{{$trash->title}}</td>
                        <td>{{ Str::limit($trash->description, 50) }}</td>
                        <td class="d-flex">
                            <span class="mr-1">
                            <form action="{{route('cetagori.trashRestore',$trash->id)}}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <button class="btn btn-outline-success" type="submit" onclick="return confirm('Are you sure you want to Restore this item?');">
                                        <i class="fas fa-trash-restore-alt"></i>
                                    </button>
                                </form>
                            </span>
                            <span>
                            <form action="{{route('cetagori.trashDelete',$trash->id)}}" method="post">
                                    @csrf
                                    @method('Delete')
                                    <button class="btn btn-outline-danger " type="submit" onclick="return confirm('Are you sure you want to parmanent delete this item?');">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </span>
                        </td>
                    </tr>
                    @endforeach
                </table>
                {{-- {{$categoris->links()}} --}}
            </div> <!-- end .table-responsive-->
        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>
@endsection

@push('js')
    <script src="{{asset('ui/backend')}}/libs/footable/footable.all.min.js"></script>

<!-- Init js -->
<script src="{{asset('ui/backend')}}/js/pages/foo-tables.init.js"></script>
@endpush